### ISSUE TITLE
Testdrive a big chunk of mp3 files

### ISSUE THREAD

**Issue by timbru31** [timbru31/mp3lyrics#19]
Test the iTunes library on my Windows machine to see if there are any unexpected errors (probably tests a couple of thousand songs)

**Comment by timbru31** [comment]
First error:

```
D:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:933:in `connect_nonblock': SSL_connect returned=1 errno=0 state=error: certificate verify failed (OpenSSL::SSL::SSLError)
        from D:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:933:in `connect'
        from D:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
        from D:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:852:in `start'
        from D:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:584:in `start'
        from E:/Coding/mp3lyrics/lib/wiki.rb:9:in `fetch'
        from E:/Coding/mp3lyrics/lib/genius.rb:13:in `get_lyrics'
        from mp3lyrics.rb:93:in `block (2 levels) in <main>'
        from D:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/ruby-mp3info-0.8.10/lib/mp3info.rb:304:in `open'
        from mp3lyrics.rb:78:in `block in <main>'
        from mp3lyrics.rb:75:in `each'
        from mp3lyrics.rb:75:in `<main>'
```

**Comment by timbru31** [comment]
![warning](https://cloud.githubusercontent.com/assets/838003/25456276/b303f766-2ad2-11e7-97fc-b455f599f2bb.png)

**Comment by timbru31** [comment]
```
E:/Coding/mp3lyrics/lib/genius.rb:17:in `get_lyrics': undefined method `delete!' for nil:NilClass (NoMethodError)
        from mp3lyrics.rb:93:in `block (2 levels) in <main>'
        from D:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/ruby-mp3info-0.8.10/lib/mp3info.rb:304:in `open'
        from mp3lyrics.rb:78:in `block in <main>'
        from mp3lyrics.rb:75:in `each'
        from mp3lyrics.rb:75:in `<main>'
```

**Comment by timbru31** [comment]
![warning](https://cloud.githubusercontent.com/assets/838003/25457124/777329e4-2ad5-11e7-8cb0-893968317586.png)

**Comment by timbru31** [comment]
Crashed
```
D:/Ruby23-x64/lib/ruby/2.3.0/uri/rfc3986_parser.rb:67:in `split': bad URI(is not URI?): http://lyrics.wikia.com/Apocalyptica:Hall_of_the_Mountain_King_(feat._Avanti_Orchestra)_[Live] (URI::InvalidURIError)
        from D:/Ruby23-x64/lib/ruby/2.3.0/uri/rfc3986_parser.rb:73:in `parse'
        from D:/Ruby23-x64/lib/ruby/2.3.0/uri/common.rb:227:in `parse'
        from E:/Coding/mp3lyrics/lib/wiki.rb:32:in `prepare_url'
        from E:/Coding/mp3lyrics/lib/wiki.rb:9:in `fetch'
        from E:/Coding/mp3lyrics/lib/lyricwikia.rb:12:in `get_lyrics'
        from mp3lyrics.rb:90:in `block (2 levels) in <main>'
        from D:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/ruby-mp3info-0.8.10/lib/mp3info.rb:304:in `open'
        from mp3lyrics.rb:78:in `block in <main>'
        from mp3lyrics.rb:75:in `each'
        from mp3lyrics.rb:75:in `<main>'
```
